const COMMAND_NOTES = "📚 Notas";
const COMMAD_NEW_NOTE = "📗 Nueva nota";
const COMMAND_EDIT_NOTE = "✏️ Editar Nota";
const COMMAND_DEL_NOTE = "🗑 Borrar Nota";
const COMMAND_RETURN = "🔙 Atras"

const ALL_COMMANDS = [
    COMMAND_NOTES,
    COMMAD_NEW_NOTE,
    COMMAND_EDIT_NOTE,
    COMMAND_DEL_NOTE,
    COMMAND_RETURN
];

export {
    ALL_COMMANDS,
    COMMAND_NOTES,
    COMMAD_NEW_NOTE,
    COMMAND_EDIT_NOTE,
    COMMAND_DEL_NOTE,
    COMMAND_RETURN
};